spring:
  application:
    name: spliterator
  datasource:
    url: jdbc:mysql://localhost:3306/spliterator
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    user: user
    password: password
